/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
public class Ques2
{
public static void main(String Args[])
{
int a=0,b=1,c=1,i;
long sum=0;
for (i=0;c<4000000;i++)
{
a=b;
b=c;
if (c%2==0)
{
sum=sum+c;
}
c=a+b;
}
System.out.println(sum);
}
}
